#!/bin/bash
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
exo-open --launch TerminalEmulator
